version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "Instructor"
      POSTGRES_USER: "VovaHun"
      POSTGRES_PASSWORD: "InstructorBD"
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"